[package]
name = "tagger"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[features]
random = ["rand"]

[dependencies]
tagmap = { git = "https://github.com/crumblingstatue/rust-tagmap" }
clap = "1.4.7"
rustyline = { git = "https://github.com/kkawakam/rustyline.git" }
rand = { version = "0.3.12", optional = true }
