[package]
name = "tagger"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[features]
random = ["rand"]
default = ["random"]

[dependencies]
tagmap = { git = "https://github.com/crumblingstatue/rust-tagmap" }
clap = "2.3"
rustyline = "0.2.2"
rand = { version = "0.3.14", optional = true }
