[package]
name = "tagger"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[features]
random = ["rand"]
default = ["random"]

[dependencies]
tagmap = { path = "/home/snake/projects/github/crumblingstatue/tagmap" }
clap = "2.3"
rustyline = "0.2.2"
rand = { version = "0.3.14", optional = true }
gtk = { version = "0.0.7", features = ["v3_10"] }
gdk-pixbuf = "*"
gdk = "*"
