reorder_imports = true
reorder_imported_names = true
write_mode = "overwrite"
fn_args_layout = "Block"
array_layout = "Block"
control_style = "Rfc"
where_style = "Rfc"
generics_indent = "Block"
fn_call_style = "Block"
